import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Linking,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, borderRadius, typography } from '../lib/theme';

const PAGES: Record<string, { title: string; icon: string; sections: { heading?: string; body: string }[] }> = {
  terms: {
    title: 'Terms of Service',
    icon: 'document-text',
    sections: [
      { heading: 'Acceptance of Terms', body: 'By downloading, installing, or using Giga3 AI ("the App"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.' },
      { heading: 'Description of Service', body: 'Giga3 AI is an AI-powered productivity platform that provides tools for academic writing, content creation, business planning, and other productivity tasks. The App uses artificial intelligence to generate text, images, and other content based on user prompts.' },
      { heading: 'AI-Generated Content Disclaimer', body: 'All content generated by Giga3 AI is produced by artificial intelligence and may contain errors, inaccuracies, or outdated information. You are solely responsible for reviewing, verifying, and editing any AI-generated content before use. Giga3 AI does not guarantee the accuracy, completeness, or suitability of any generated content for any purpose.' },
      { heading: 'Academic Integrity', body: 'If you use Giga3 AI for academic purposes, you are responsible for ensuring compliance with your institution\'s academic integrity policies. AI-generated content should be used as a learning aid and reference tool, not submitted as your own original work without proper disclosure and review.' },
      { heading: 'User Responsibilities', body: 'You agree to: (1) use the App only for lawful purposes; (2) not use the App to generate harmful, misleading, or inappropriate content; (3) not attempt to reverse-engineer the App; (4) not share your account credentials with others; (5) verify all AI-generated content before relying on it for important decisions.' },
      { heading: 'Earn & Referral Program', body: 'The Earn tab provides platform-based rewards and promotional incentives. Earnings shown are platform rewards, not guaranteed income. Reward amounts and availability are subject to change. Withdrawal functionality will be enabled when payment integration is available. Giga3 AI makes no promises of income or financial returns.' },
      { heading: 'Subscriptions & Payments', body: 'Free plan users receive a limited number of daily AI generations. Pro subscriptions, when available, will be billed through Google Play or Apple App Store. Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current billing period. Refunds are subject to the respective app store policies.' },
      { heading: 'Intellectual Property', body: 'You retain ownership of content you create using Giga3 AI. The App, its design, code, and branding are the intellectual property of Giga3 AI and its creators. You may not copy, modify, or redistribute the App without permission.' },
      { heading: 'Limitation of Liability', body: 'Giga3 AI is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the App, including but not limited to: reliance on AI-generated content, academic consequences, financial decisions, or business outcomes based on App output.' },
      { heading: 'Termination', body: 'We reserve the right to suspend or terminate your access to the App at any time for violation of these terms or for any other reason at our discretion.' },
      { heading: 'Changes to Terms', body: 'We may update these Terms of Service from time to time. Continued use of the App after changes constitutes acceptance of the updated terms.' },
      { heading: 'Contact', body: 'For questions about these terms, contact us at ayiiga3@gmail.com.' },
      { body: 'Last updated: January 2025' },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    icon: 'shield-checkmark',
    sections: [
      { heading: 'Introduction', body: 'Giga3 AI ("we", "our", "us") respects your privacy. This Privacy Policy explains how we collect, use, and protect your information when you use our mobile application.' },
      { heading: 'Information We Collect', body: 'Account Information: If you sign in with Google or Apple, we receive your name and email address.\n\nUsage Data: We collect anonymous usage statistics such as which tools you use, generation counts, and app interactions to improve the service.\n\nDevice Information: A randomly generated device identifier is stored locally on your device for tracking usage limits and earning rewards.\n\nContent: Your prompts and generated results are processed to provide the service. Chat conversations are stored if you are signed in.' },
      { heading: 'How We Use Your Information', body: 'We use your information to: (1) provide and improve the App\'s AI generation services; (2) track daily usage limits; (3) manage your account and preferences; (4) process referral rewards and earning tracking; (5) send important service notifications; (6) analyze usage patterns to improve the App.' },
      { heading: 'Data Storage', body: 'Most user preferences and recent activity are stored locally on your device using secure storage. Chat conversations and account data are stored on secure cloud servers (Convex). We do not sell your personal data to third parties.' },
      { heading: 'Third-Party Services', body: 'We use the following third-party services:\n\n• Google Sign-In / Apple Sign-In for authentication\n• Convex for secure database storage\n• RevenueCat for subscription management\n• AI language model APIs for content generation\n\nEach service has its own privacy policy governing their data practices.' },
      { heading: 'Data Retention', body: 'Your account data is retained as long as your account is active. You can request deletion of your data at any time through the Profile > Delete Account option. Locally stored data can be cleared by uninstalling the App.' },
      { heading: 'Your Rights', body: 'You have the right to: (1) access the personal data we hold about you; (2) request correction of inaccurate data; (3) request deletion of your data; (4) withdraw consent for data processing; (5) export your data. To exercise these rights, contact us at ayiiga3@gmail.com.' },
      { heading: 'Children\'s Privacy', body: 'Giga3 AI is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If you believe we have collected such information, please contact us immediately.' },
      { heading: 'Security', body: 'We implement reasonable security measures to protect your data, including encrypted connections, secure cloud storage, and access controls. However, no method of electronic storage is 100% secure.' },
      { heading: 'Changes to This Policy', body: 'We may update this Privacy Policy from time to time. We will notify you of significant changes through the App or via email.' },
      { heading: 'Contact Us', body: 'For privacy-related questions or data requests, contact:\n\nEmail: ayiiga3@gmail.com\nDeveloper: Ayiiga Benard Issaka\nLocation: Ghana' },
      { body: 'Last updated: January 2025' },
    ],
  },
  about: {
    title: 'About Giga3 AI',
    icon: 'information-circle',
    sections: [
      { heading: 'Our Mission', body: 'Giga3 AI is an AI-powered productivity platform designed to empower students, tutors, researchers, creators, and entrepreneurs — especially across Africa and the developing world — with accessible, intelligent tools for learning, creating, and building.' },
      { heading: 'What We Do', body: 'We provide 30+ AI-powered tools spanning:\n\n• Academic Writing — essays, theses, research papers, literature reviews\n• Study Tools — study planners, flashcards, past question generators\n• Content Creation — captions, scripts, hooks, books\n• Business Tools — business plans, pitch decks, marketing copy\n• General Productivity — resumes, emails, course outlines' },
      { heading: 'Built for Africa', body: 'Giga3 AI includes localized support for African examination systems including WAEC, BECE, and WASSCE. Our tools are designed to work efficiently on low-to-mid-range Android devices common across Africa.' },
      { heading: 'The Team', body: 'Built by Ayiiga Benard Issaka, an educator from Ghana focused on empowering students, creators, and entrepreneurs with AI tools.' },
      { heading: 'Important Disclaimers', body: '• AI-generated content may contain errors — always verify before use\n• Academic tools are learning aids, not substitutes for original work\n• Earnings in the Earn tab are platform rewards, not guaranteed income\n• Pro subscription features are being prepared for launch' },
      { heading: 'Contact & Support', body: 'Email: ayiiga3@gmail.com\n\nWe welcome feedback, feature requests, and partnership inquiries.' },
      { body: '© Giga3 AI — Built in Africa\nVersion 2.0.0' },
    ],
  },
  feedback: {
    title: 'Send Feedback',
    icon: 'chatbox',
    sections: [
      { heading: 'We Value Your Feedback', body: 'Your feedback helps us improve Giga3 AI. Please share your thoughts, report bugs, or suggest new features.' },
      { heading: 'Report a Bug', body: 'If you encountered a bug or error, please describe:\n\n1. What you were doing when the issue occurred\n2. What you expected to happen\n3. What actually happened\n4. Your device model and Android version\n\nSend your report to ayiiga3@gmail.com with the subject "Bug Report".' },
      { heading: 'Feature Requests', body: 'Have an idea for a new tool or feature? We\'d love to hear it! Send your suggestion to ayiiga3@gmail.com with the subject "Feature Request".' },
      { heading: 'General Feedback', body: 'For general feedback, compliments, or concerns, email us at ayiiga3@gmail.com with the subject "Feedback".' },
      { heading: 'Response Time', body: 'We aim to respond to all feedback within 48 hours. Thank you for helping us improve Giga3 AI!' },
    ],
  },
  'earn-rules': {
    title: 'Earning Rules',
    icon: 'cash',
    sections: [
      { heading: 'How Platform Rewards Work', body: 'The Giga3 AI Earn tab provides platform-based rewards and promotional incentives. These are not guaranteed income or employment compensation.' },
      { heading: 'Daily Task Rewards', body: 'Complete daily tasks within the app to earn platform reward points. Tasks include logging in, generating content, sharing the app, and completing quizzes. Reward amounts are set by the platform and may change at any time.' },
      { heading: 'Referral Rewards', body: 'Share your unique referral link with friends. When someone signs up using your link, you earn a one-time referral reward (currently GHS 5 per signup). Referral rewards are subject to verification and may be adjusted.' },
      { heading: 'Affiliate Products', body: 'Recommended products in the Earn tab may include affiliate links. Commissions are earned when users make purchases through your affiliate links. Commission rates vary by product and are set by the product provider.' },
      { heading: 'Withdrawal Rules', body: '• Minimum withdrawal amount: GHS 50\n• Withdrawals will be enabled when payment integration (Mobile Money, PayPal) goes live\n• All earnings are subject to verification before withdrawal\n• Fraudulent activity will result in account suspension and forfeiture of earnings' },
      { heading: 'Important Disclaimers', body: '• Platform rewards are promotional incentives, not guaranteed income\n• Earning amounts may change without notice\n• Giga3 AI does not guarantee any specific level of earnings\n• Rewards are subject to platform availability and terms\n• Tax obligations on earnings are your responsibility' },
      { heading: 'Questions?', body: 'Contact ayiiga3@gmail.com for questions about the earning program.' },
    ],
  },
};

type Props = {
  route: { params: { pageId: string } };
  navigation: any;
};

export default function InfoScreen({ route, navigation }: Props) {
  const { pageId } = route.params;
  const page = PAGES[pageId];

  if (!page) {
    return (
      <View style={styles.container}>
        <SafeAreaView style={styles.safeArea}>
          <Text style={styles.errorText}>Page not found</Text>
        </SafeAreaView>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <SafeAreaView edges={['top', 'bottom']} style={styles.safeArea}>
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backBtn}
            onPress={() => navigation.goBack()}
            hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
          >
            <Ionicons name="chevron-back" size={24} color={colors.textPrimary} />
          </TouchableOpacity>
          <View style={[styles.headerIcon, { backgroundColor: colors.goldMuted }]}>
            <Ionicons name={page.icon as any} size={16} color={colors.gold} />
          </View>
          <Text style={styles.headerTitle}>{page.title}</Text>
        </View>

        <ScrollView
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          {page.sections.map((section, idx) => (
            <View key={idx} style={styles.section}>
              {section.heading && (
                <Text style={styles.sectionHeading}>{section.heading}</Text>
              )}
              <Text style={styles.sectionBody}>{section.body}</Text>
            </View>
          ))}

          {(pageId === 'feedback' || pageId === 'about' || pageId === 'earn-rules') && (
            <TouchableOpacity
              style={styles.emailBtn}
              activeOpacity={0.8}
              onPress={() => {
                const subject = pageId === 'feedback' ? 'Giga3%20AI%20Feedback' : 'Giga3%20AI%20Inquiry';
                Linking.openURL(`mailto:ayiiga3@gmail.com?subject=${subject}`).catch(() => {});
              }}
            >
              <Ionicons name="mail" size={18} color={colors.textInverse} />
              <Text style={styles.emailBtnText}>Email ayiiga3@gmail.com</Text>
            </TouchableOpacity>
          )}

          <View style={{ height: 40 }} />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  safeArea: { flex: 1 },
  errorText: { ...typography.body, color: colors.error, textAlign: 'center', marginTop: 100 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  backBtn: { padding: spacing.sm },
  headerIcon: {
    width: 32,
    height: 32,
    borderRadius: borderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { ...typography.h3, color: colors.textPrimary, flex: 1 },
  scrollContent: { padding: spacing.lg },
  section: { marginBottom: spacing.xl },
  sectionHeading: {
    ...typography.bodyMedium,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  sectionBody: {
    ...typography.body,
    color: colors.textSecondary,
    lineHeight: 24,
  },
  emailBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.gold,
    paddingVertical: spacing.lg,
    borderRadius: borderRadius.full,
    marginTop: spacing.md,
  },
  emailBtnText: { ...typography.bodyMedium, color: colors.textInverse },
});